name = "bumblebee-hive"
main = "src/index.ts"
compatibility_date = "2026-05-26"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true

[triggers]
crons = ["17 */6 * * *"]

[[r2_buckets]]
binding = "RAW_BATCHES"
bucket_name = "bumblebee-hive-raw"

[[d1_databases]]
binding = "DB"
database_name = "bumblebee-hive"
database_id = "1d677871-23e1-46df-96ff-caae9d430fad"

[[queues.producers]]
binding = "NORMALIZE_QUEUE"
queue = "bumblebee-hive-normalize"

[[queues.consumers]]
queue = "bumblebee-hive-normalize"
max_batch_size = 10
max_batch_timeout = 30
